# Generated by Django 3.2.7 on 2021-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.FileField(upload_to='media/category'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.FileField(default='media/stud.jpg', upload_to='media/teacher'),
        ),
    ]
