# Generated by Django 3.2.7 on 2021-11-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.FileField(default='static/stud.jpg', null=True, upload_to='media/teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.subject'),
        ),
    ]
